var math =75.25;
var bio = 65;
var chem =80;
var phy =35.45;
var bangla =99.50;
var totalMarks = math + bio + chem + phy + bangla;
console.log(totalMarks);
var avarage = totalMarks/5;
console.log(avarage);
var decimal = avarage.toFixed(2);
console.log(decimal);
