var math =75.25;
var bio = 65;
var chem =80;
var phy =35.45;
var bangla =99.50;
var sum = math + bio + chem + phy + bangla;
console.log(sum);
var avarage = sum/5;
console.log(avarage);
var decimal = avarage.toFixed(2);
console.log(decimal);
